sudo: required
env:
- BOOK_LANG=fr
- BOOK_LANG=en
services:
- docker
before_install:
- docker pull tianon/latex
script:
- docker run -it -v $(pwd)/src:/src tianon/latex bash -c "cd /src/$BOOK_LANG && pdflatex master.tex
  && pdflatex master.tex"
before_deploy:
- mkdir -p deploy/$TRAVIS_BRANCH/$BOOK_LANG
- cp $(pwd)/src/$BOOK_LANG/master.pdf deploy/$TRAVIS_BRANCH/$BOOK_LANG/master.pdf
deploy:
  provider: s3
  access_key_id: AKIAJSYX42GDKOI7KPFQ
  secret_access_key:
    secure: OkLQlU3j0LqDa1nTlWTrpeJ491zxpVwGBOMwS/4r3JF21yzVZslhMDCGps5JUrn4pTm+SV9XwWlF9JGMZnkbb5FLdmfgsKbCEoCOasR+G2DiiV+8Me5d3FabZ/GDbreAXEXJSbIDSMS4G7CznPMyFA8r22VVR8+2BJrigdmAehc=
  bucket: lecons
  local-dir: deploy
  acl: public_read
  on:
    repo: apetresc/Lecons-Sur-La-Theorie-Generale-Des-Surfaces
  skip_cleanup: true
